server:
  port: 8080
spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1522/xepdb1
    username: ${DB_USERNAME:MATRICULADB}
    password: ${DB_PASSWORD:1234567}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
matricula:
  costo-credito: 120.00
logging:
  level:
    pe.edu.upeu.MatriculaBackend: INFO
