spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
matricula:
  costo-credito: ${MATRICULA_COSTO_CREDITO:120.00}
