-- Ejecutar conectado al servicio xepdb1 con un usuario administrador (SYSTEM/SYSDBA).
CREATE USER MATRICULADB IDENTIFIED BY "1234567";
GRANT CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE VIEW TO MATRICULADB;
ALTER USER MATRICULADB QUOTA UNLIMITED ON USERS;
